Olha ai como ficou, tá feio o codigo mas ta funcionando
pinho/matrizes-js pull request #1
Opened 2021-01-08 02:23 UTC by wagnernegrao

2021-01-09 23:05 UTC, pinho requested changes
Bug é resolvido ao mover a chamada de ```reflectionReverse()``` pra depois do loop while

2021-01-09 23:05 UTC, pinho commented on src/bresenham.js
> +        reflectionReverse();
Debuguei e descobri que o problema é o que reflexão é feita em todos os pontos a cada iteração, e pode ser solucionado movendo essa linha pra depois do término do while (assim a reflexão pro octante original vai ser feita só quando todos os pontos já estiverem definidos).

2021-01-10 18:04 UTC, wagnernegrao commented on src/bresenham.js
> +        reflectionReverse();
Ok, vou fazer essas mudanças

2021-01-10 18:18 UTC, wagnernegrao commented on src/bresenham.js
> +        reflectionReverse();
correção feita

2021-01-10 21:54 UTC, merged